import type { MbtiQuestion, MbtiTypeInfo } from './mbti';

export const programmingQuestions: MbtiQuestion[] = [
  // EI — 1-15
  { id: 1, text: 'ฉันชอบ pair programming หรือพูดคุยขณะเขียนโค้ดมากกว่านั่งคิดคนเดียวเงียบๆ', dimension: 'EI', pole: 'E' },
  { id: 2, text: 'ฉันรู้สึกมีพลังขึ้นทุกครั้งที่ได้ demo ฟีเจอร์ใหม่ให้ทีมหรือลูกค้าดู', dimension: 'EI', pole: 'E' },
  { id: 3, text: 'หลังประชุม sprint review ทั้งวัน ฉันต้องการเวลาเขียนโค้ดคนเดียวเงียบๆ เพื่อฟื้นพลัง', dimension: 'EI', pole: 'I' },
  { id: 4, text: 'ฉันชอบใส่หูฟังแล้วโฟกัส debug ปัญหาของตัวเองโดยไม่อยากให้ใครรบกวน', dimension: 'EI', pole: 'I' },
  { id: 5, text: 'ฉันกล้าเสนอไอเดียทาง technical ในที่ประชุม standup โดยไม่ลังเล', dimension: 'EI', pole: 'E' },
  { id: 6, text: 'ฉันชอบเขียน design doc สรุปความคิดของตัวเองก่อน แล้วค่อยนำไปแชร์กับทีม', dimension: 'EI', pole: 'I' },
  { id: 7, text: 'การได้ brainstorm สถาปัตยกรรมระบบร่วมกับทีมทำให้ไอเดียของฉันแน่นขึ้น', dimension: 'EI', pole: 'E' },
  { id: 8, text: 'ฉันถนัดคิดแก้ปัญหา algorithm คนเดียวมากกว่าทำเป็นกลุ่มใหญ่', dimension: 'EI', pole: 'I' },
  { id: 9, text: 'ฉันชอบเดินไปคุยกับทีมเพื่อเช็คความคืบหน้าของงานตลอดทั้งวัน', dimension: 'EI', pole: 'E' },
  { id: 10, text: 'ฉันชอบทำงานในห้องที่เงียบสงบมากกว่า open office ที่มีคนคุยกันตลอดเวลา', dimension: 'EI', pole: 'I' },
  { id: 11, text: 'ฉันชอบเป็นคนเปิดประเด็นพูดคุยใน code review หรือ tech talk', dimension: 'EI', pole: 'E' },
  { id: 12, text: 'ฉันคิดโค้ดได้ดีที่สุดเวลาอยู่คนเดียวในที่ที่ไม่มีใครพูดคุย', dimension: 'EI', pole: 'I' },
  { id: 13, text: 'ฉันสนุกกับการพรีเซนต์ผลงานทาง technical ต่อหน้าทีมหรือผู้บริหาร', dimension: 'EI', pole: 'E' },
  { id: 14, text: 'ฉันชอบส่ง pull request ให้ทีมรีวิวผ่านข้อความมากกว่าอธิบายสดต่อหน้าคนหมู่มาก', dimension: 'EI', pole: 'I' },
  { id: 15, text: 'ฉันรู้สึกตื่นเต้นทุกครั้งที่ได้ทำงานร่วมกับคนหลายๆ คนใน sprint เดียวกัน', dimension: 'EI', pole: 'E' },

  // SN — 16-30
  { id: 16, text: 'ฉันให้ความสำคัญกับรายละเอียด edge case และ unit test มากกว่าภาพรวมของ feature', dimension: 'SN', pole: 'S' },
  { id: 17, text: 'ฉันชอบทดลอง framework หรือเทคโนโลยีใหม่ที่ยังไม่ mature มากกว่าใช้ของที่พิสูจน์แล้วว่าได้ผล', dimension: 'SN', pole: 'N' },
  { id: 18, text: 'ฉันเชื่อมั่นในการใช้ technology ที่ stable และมีคนใช้แพร่หลายมากกว่าทดลองเทรนด์ใหม่', dimension: 'SN', pole: 'S' },
  { id: 19, text: 'ฉันมักมองเห็นความเป็นไปได้ใหม่ๆ ของระบบที่คนอื่นยังไม่ทันคิดถึง', dimension: 'SN', pole: 'N' },
  { id: 20, text: 'ฉันชอบทำงานที่มี requirement และตัวอย่างอ้างอิงชัดเจนมากกว่าต้องคิดจากศูนย์', dimension: 'SN', pole: 'S' },
  { id: 21, text: 'ฉันสนใจจินตนาการถึง architecture ใหม่ที่ยังไม่มีใครลองทำมากกว่าทำตามแบบที่มีอยู่', dimension: 'SN', pole: 'N' },
  { id: 22, text: 'ฉันตรวจเช็คความถูกต้องของ spec และ API contract ทุกฟิลด์อย่างละเอียด', dimension: 'SN', pole: 'S' },
  { id: 23, text: 'ฉันชอบเชื่อมโยงไอเดียจากหลายสาขามาออกแบบ solution ใหม่ที่ไม่เคยมีใครทำ', dimension: 'SN', pole: 'N' },
  { id: 24, text: 'ฉันให้ความสำคัญกับข้อมูล log และ metric ที่จับต้องได้มากกว่าไอเดียที่ยังเป็นนามธรรม', dimension: 'SN', pole: 'S' },
  { id: 25, text: 'ฉันมักเสนอแนวทางแก้ปัญหาที่แตกต่างจากกรอบเดิมๆ ของ codebase', dimension: 'SN', pole: 'N' },
  { id: 26, text: 'ฉันชอบ maintain และปรับปรุงระบบที่มีอยู่ให้ดีขึ้น มากกว่าออกแบบ architecture ใหม่ทั้งหมด', dimension: 'SN', pole: 'S' },
  { id: 27, text: 'ฉันชอบตั้งคำถามว่า "จะเป็นอย่างไรถ้า..." มากกว่าทำตามวิธีที่คุ้นเคยในทีม', dimension: 'SN', pole: 'N' },
  { id: 28, text: 'ฉันใส่ใจกับความถูกต้องของ syntax และ format ของโค้ดก่อน commit ทุกครั้ง', dimension: 'SN', pole: 'S' },
  { id: 29, text: 'ฉันชอบสร้างสิ่งที่ยังไม่มีใครเคยทำมาก่อนมากกว่าปรับปรุงของเดิมที่มีอยู่แล้ว', dimension: 'SN', pole: 'N' },
  { id: 30, text: 'ฉันให้ความสำคัญกับขั้นตอนการทำงานที่พิสูจน์แล้วว่าได้ผลจริงในอดีตมากกว่าทดลองวิธีใหม่', dimension: 'SN', pole: 'S' },

  // TF — 31-45
  { id: 31, text: 'เมื่อ code review ฉันชี้ปัญหาตรงๆ ตามหลักเหตุผลแม้จะทำให้บรรยากาศอึดอัด', dimension: 'TF', pole: 'T' },
  { id: 32, text: 'ฉันให้ความสำคัญกับความรู้สึกของเพื่อนร่วมทีมเวลาให้ feedback เกี่ยวกับโค้ดของเขา', dimension: 'TF', pole: 'F' },
  { id: 33, text: 'ฉันตัดสินใจ merge code โดยดูจากผลเทสต์และ metric มากกว่าความรู้สึกอยากให้กำลังใจเพื่อน', dimension: 'TF', pole: 'T' },
  { id: 34, text: 'ฉันเลือกประนีประนอมเรื่อง technical decision เพื่อรักษาความสัมพันธ์ที่ดีในทีม', dimension: 'TF', pole: 'F' },
  { id: 35, text: 'ฉันให้น้ำหนักกับ performance metric มากกว่าความรู้สึกภูมิใจของทีมที่ทำฟีเจอร์นั้นสำเร็จ', dimension: 'TF', pole: 'T' },
  { id: 36, text: 'ฉันมักถามตัวเองว่างานนี้ทำให้ทีมรู้สึกอย่างไรมากกว่าถามว่ามันมีประสิทธิภาพแค่ไหน', dimension: 'TF', pole: 'F' },
  { id: 37, text: 'ฉันวิเคราะห์ข้อดีข้อเสียของแต่ละ technical option อย่างเป็นระบบก่อนตัดสินใจ', dimension: 'TF', pole: 'T' },
  { id: 38, text: 'ฉันใส่ใจว่าการตัดสินใจเรื่อง deadline จะกระทบความรู้สึกของเพื่อนในทีมหรือไม่', dimension: 'TF', pole: 'F' },
  { id: 39, text: 'ฉันเลือกฟีเจอร์ที่มี data รองรับชัดเจนมากกว่าฟีเจอร์ที่ทีมรู้สึกอยากทำเพราะมันท้าทาย', dimension: 'TF', pole: 'T' },
  { id: 40, text: 'ฉันมักเลือกแนวทางที่ทำให้ทุกคนในทีมรู้สึกสบายใจที่สุดมากกว่าทางที่มีเหตุผลรองรับมากสุด', dimension: 'TF', pole: 'F' },
  { id: 41, text: 'ฉันเชื่อว่าการแก้ปัญหาทางเทคนิคให้ตรงจุดสำคัญกว่าการประชุมเพื่อสร้างความเข้าใจร่วมกันในทีม', dimension: 'TF', pole: 'T' },
  { id: 42, text: 'ฉันรับฟังคำวิจารณ์ตรงๆ เกี่ยวกับโค้ดของตัวเองได้ แต่ก็พยายามพูดให้กำลังใจคนอื่นเสมอเวลา review', dimension: 'TF', pole: 'F' },
  { id: 43, text: 'ฉันเลือกใช้เหตุผลและข้อมูลล้วนๆ อธิบายปัญหาทางเทคนิคมากกว่าปรับคำพูดให้คนฟังรู้สึกดี', dimension: 'TF', pole: 'T' },
  { id: 44, text: 'ฉันสนใจดูแลบรรยากาศและกำลังใจของทีมหลังเดดไลน์หนักๆ มากกว่าทบทวนแค่ตัวเลขผลงาน', dimension: 'TF', pole: 'F' },
  { id: 45, text: 'ฉันให้ความสำคัญกับความถูกต้องของ test case มากกว่าความรู้สึกของคนที่เขียนโค้ดนั้นมาก่อน', dimension: 'TF', pole: 'T' },

  // JP — 46-60
  { id: 46, text: 'ฉันชอบวางแผน sprint และ task ให้ชัดเจนก่อนเริ่มเขียนโค้ดจริง', dimension: 'JP', pole: 'J' },
  { id: 47, text: 'ฉันทำงานได้ดีแม้ requirement ยังไม่ชัดเจน และชอบค้นพบทิศทางระหว่างพัฒนา', dimension: 'JP', pole: 'P' },
  { id: 48, text: 'ฉันชอบส่งงานก่อนเดดไลน์เพื่อมีเวลาเหลือสำหรับ refactor และทดสอบเพิ่ม', dimension: 'JP', pole: 'J' },
  { id: 49, text: 'ฉันปรับ scope ของงานได้ง่ายเมื่อ requirement เปลี่ยนกะทันหัน', dimension: 'JP', pole: 'P' },
  { id: 50, text: 'ฉันรู้สึกอุ่นใจเมื่อมี timeline และ milestone ที่กำหนดไว้ล่วงหน้าอย่างชัดเจน', dimension: 'JP', pole: 'J' },
  { id: 51, text: 'ฉันชอบเปิดทางเลือกด้าน technical ไว้หลายแบบจนถึงวินาทีสุดท้ายก่อนตัดสินใจ', dimension: 'JP', pole: 'P' },
  { id: 52, text: 'ฉันชอบงานที่มีขอบเขตและ spec ชัดเจนมากกว่างานที่เปิดกว้างไม่มีกรอบ', dimension: 'JP', pole: 'J' },
  { id: 53, text: 'ฉันสนุกกับการทำงานแบบไม่มีแผนตายตัวและปล่อยให้ไอเดียพาไปเรื่อยๆ', dimension: 'JP', pole: 'P' },
  { id: 54, text: 'ฉันทำ checklist ของงานและติดตามความคืบหน้าใน task board อย่างเป็นขั้นเป็นตอน', dimension: 'JP', pole: 'J' },
  { id: 55, text: 'ฉันมักทำงานหลายอย่างพร้อมกันโดยสลับไปมาตามแรงบันดาลใจในตอนนั้น', dimension: 'JP', pole: 'P' },
  { id: 56, text: 'ฉันรู้สึกไม่สบายใจถ้างานยังไม่ปิดจบเป็น pull request ที่สมบูรณ์ก่อนถึงกำหนดส่ง', dimension: 'JP', pole: 'J' },
  { id: 57, text: 'ฉันชอบแก้ไขโค้ดต่อเนื่องเรื่อยๆ แม้จะ merge ไปแล้วถ้ามีไอเดียใหม่เข้ามา', dimension: 'JP', pole: 'P' },
  { id: 58, text: 'ฉันวางลำดับขั้นตอนการพัฒนาไว้อย่างเป็นระบบตั้งแต่ design จนถึง deploy', dimension: 'JP', pole: 'J' },
  { id: 59, text: 'ฉันชอบความยืดหยุ่นใน roadmap มากกว่าทำตามแผนที่กำหนดไว้ตายตัว', dimension: 'JP', pole: 'P' },
  { id: 60, text: 'ฉันใส่ใจปิด ticket ทุกใบให้เรียบร้อยตามกำหนดเวลาที่ตกลงกันไว้เสมอ', dimension: 'JP', pole: 'J' },

  // EI — 61-75
  { id: 61, text: 'ฉันชอบพาสมาชิกใหม่ทัวร์ codebase และแนะนำทีมด้วยตัวเองมากกว่าปล่อยให้อ่าน documentation เอง', dimension: 'EI', pole: 'E' },
  { id: 62, text: 'ฉันชอบทำงาน remote แบบ async เขียนคำตอบใน ticket มากกว่าต้องเข้าประชุมวิดีโอคุยสด', dimension: 'EI', pole: 'I' },
  { id: 63, text: 'ฉันสนุกกับบรรยากาศ hackathon ที่มีคนคึกคักระดมไอเดียกันตลอดเวลา', dimension: 'EI', pole: 'E' },
  { id: 64, text: 'เวลาเกิด incident ฉันชอบไล่ดู log และแก้ปัญหาคนเดียวก่อนที่จะเรียกคนอื่นเข้ามาช่วย', dimension: 'EI', pole: 'I' },
  { id: 65, text: 'ฉันชอบเป็นคน volunteer รับสายตอน on-call incident call เพื่อได้พูดคุยประสานงานกับทีมสด', dimension: 'EI', pole: 'E' },
  { id: 66, text: 'ฉันชอบเขียนบทความหรือโน้ตสรุปความรู้แชร์ในทีมมากกว่าพูดสอนสดต่อหน้าคน', dimension: 'EI', pole: 'I' },
  { id: 67, text: 'ฉันชอบรับหน้าที่ mentor จับคู่นั่งสอนน้องใหม่แบบตัวต่อตัวสดๆ', dimension: 'EI', pole: 'E' },
  { id: 68, text: 'ฉันรู้สึกเหนื่อยล้าหลังจากขึ้นพูด conference talk ทั้งวันและต้องการเวลาอยู่คนเดียวฟื้นพลัง', dimension: 'EI', pole: 'I' },
  { id: 69, text: 'ฉันชอบพิมพ์คุยใน Slack แบบ real-time ต่อเนื่องกับเพื่อนร่วมทีมตลอดวันทำงาน', dimension: 'EI', pole: 'E' },
  { id: 70, text: 'ฉันชอบอ่าน thread และคิดคำตอบให้รอบคอบก่อนพิมพ์ตอบในแชทของทีม', dimension: 'EI', pole: 'I' },
  { id: 71, text: 'ฉัน active พูดแสดงความเห็นในวง retrospective ทุกครั้งที่มีประเด็นน่าพูดถึง', dimension: 'EI', pole: 'E' },
  { id: 72, text: 'ฉันมักเขียนความเห็นเกี่ยวกับ retrospective ลงในเอกสารมากกว่าพูดออกมาในที่ประชุม', dimension: 'EI', pole: 'I' },
  { id: 73, text: 'ฉันชอบชวนเพื่อนร่วมทีมไปกินข้าวหรือคุยเล่นนอกเรื่องงานระหว่างวันทำงาน', dimension: 'EI', pole: 'E' },
  { id: 74, text: 'ฉันทำงานได้ดีที่สุดเมื่อไม่มีการแจ้งเตือนหรือข้อความจากทีมเข้ามารบกวนระหว่างเขียนโค้ด', dimension: 'EI', pole: 'I' },
  { id: 75, text: 'ฉันชอบเป็นตัวแทนทีมไปคุยประสานงานกับทีมอื่นหรือฝ่ายที่เกี่ยวข้องด้วยตัวเอง', dimension: 'EI', pole: 'E' },

  // SN — 76-90
  { id: 76, text: 'ฉันชอบอ่าน documentation ทีละขั้นตอนตามลำดับก่อนเริ่มใช้ library ใหม่จริงจัง', dimension: 'SN', pole: 'S' },
  { id: 77, text: 'ฉันชอบเปิด library ใหม่มาลองใช้เลยแล้วค่อยหาความหมายจากพฤติกรรมที่เกิดขึ้นจริง', dimension: 'SN', pole: 'N' },
  { id: 78, text: 'ฉันเลือกใช้ pattern การเขียนโค้ดที่ทีมใช้กันอยู่แล้วมากกว่าคิดรูปแบบใหม่ขึ้นมาเอง', dimension: 'SN', pole: 'S' },
  { id: 79, text: 'ฉันมักมองเห็นวิธีจัดโครงสร้างข้อมูลแบบใหม่ที่ต่างจาก schema เดิมที่ทีมใช้อยู่', dimension: 'SN', pole: 'N' },
  { id: 80, text: 'เวลา debug ฉันยึดตาม stack trace และ error message ที่ปรากฏจริงเป็นหลัก', dimension: 'SN', pole: 'S' },
  { id: 81, text: 'เวลา debug ฉันมักเดา root cause จากความรู้สึกและประสบการณ์ก่อนไปดูรายละเอียด log', dimension: 'SN', pole: 'N' },
  { id: 82, text: 'ฉันประเมินเวลาทำงานของ task ใหม่โดยอ้างอิงจาก velocity และข้อมูลของ sprint ที่ผ่านมา', dimension: 'SN', pole: 'S' },
  { id: 83, text: 'ฉันจินตนาการถึงศักยภาพของฟีเจอร์ในอนาคตมากกว่ายึดตัวเลขจาก sprint ที่ผ่านมา', dimension: 'SN', pole: 'N' },
  { id: 84, text: 'ฉันชอบเรียนเทคโนโลยีใหม่ผ่าน tutorial ที่มีตัวอย่างโค้ดที่รันได้จริงทีละขั้น', dimension: 'SN', pole: 'S' },
  { id: 85, text: 'ฉันชอบอ่านภาพรวมแนวคิดของเทคโนโลยีใหม่ก่อนแล้วค่อยปะติดปะต่อรายละเอียดเอง', dimension: 'SN', pole: 'N' },
  { id: 86, text: 'ฉันเลือก refactor โค้ดทีละขั้นแบบมีแผนที่ตรวจสอบได้ มากกว่ารื้อเขียนใหม่ทั้งหมด', dimension: 'SN', pole: 'S' },
  { id: 87, text: 'ฉันมักอยากรื้อออกแบบระบบใหม่ทั้งหมดเมื่อเห็นว่ามีวิธีที่ดีกว่าของเดิม', dimension: 'SN', pole: 'N' },
  { id: 88, text: 'ใน retrospective ฉันเสนอวิธีแก้ปัญหากระบวนการทำงานที่จับต้องได้และทำได้ทันที', dimension: 'SN', pole: 'S' },
  { id: 89, text: 'ใน retrospective ฉันมักเสนอวิสัยทัศน์อนาคตของทีมมากกว่าการแก้ปัญหาเฉพาะหน้า', dimension: 'SN', pole: 'N' },
  { id: 90, text: 'ฉันเลือกใช้ library ที่มี track record ยาวนานและมีคนใช้งานจริงจำนวนมาก', dimension: 'SN', pole: 'S' },

  // TF — 91-105
  { id: 91, text: 'ในการทำ postmortem ฉันมุ่งวิเคราะห์หาสาเหตุเชิงระบบมากกว่าห่วงว่าใครจะรู้สึกถูกตำหนิ', dimension: 'TF', pole: 'T' },
  { id: 92, text: 'ในการทำ postmortem ฉันระวังคำพูดไม่ให้ใครในทีมรู้สึกว่าถูกตำหนิเป็นการส่วนตัว', dimension: 'TF', pole: 'F' },
  { id: 93, text: 'ฉันเลือก priority แก้ tech debt ตามผลกระทบเชิงตัวเลขที่มันสร้างให้ระบบมากกว่าเสียงเรียกร้องของทีม', dimension: 'TF', pole: 'T' },
  { id: 94, text: 'ฉันฟังเสียงความเหนื่อยล้าของทีมประกอบการตัดสินใจว่าจะแก้ tech debt ตอนไหน', dimension: 'TF', pole: 'F' },
  { id: 95, text: 'เวลาให้ feedback น้องใหม่ ฉันชี้จุดผิดพลาดตรงๆ ตามความจริงแม้เขาจะรู้สึกไม่ดี', dimension: 'TF', pole: 'T' },
  { id: 96, text: 'เวลาให้ feedback น้องใหม่ ฉันเลือกคำพูดที่ให้กำลังใจควบคู่กับการชี้จุดที่ต้องแก้ไข', dimension: 'TF', pole: 'F' },
  { id: 97, text: 'ฉันเลือก algorithm ที่มี performance ดีที่สุดแม้จะอ่านยากกว่าของเดิมที่ทีมคุ้นเคย', dimension: 'TF', pole: 'T' },
  { id: 98, text: 'ฉันเลือก solution ที่ทีมเข้าใจและรู้สึกสบายใจร่วมกันมากกว่า solution ที่มี performance ดีที่สุด', dimension: 'TF', pole: 'F' },
  { id: 99, text: 'เวลาทีมมีข้อถกเถียงเรื่อง code style ฉันยึดตาม benchmark และมาตรฐานสากลเป็นตัวตัดสิน', dimension: 'TF', pole: 'T' },
  { id: 100, text: 'เวลาทีมมีข้อถกเถียงเรื่อง code style ฉันหาข้อสรุปที่ทุกคนในทีมยอมรับร่วมกันได้', dimension: 'TF', pole: 'F' },
  { id: 101, text: 'ฉันตัดสินใจเลือกใช้หรือเลิกใช้ dependency ใดๆ โดยดูจากข้อมูลประสิทธิภาพล้วนๆ', dimension: 'TF', pole: 'T' },
  { id: 102, text: 'ฉันคำนึงถึงความรู้สึกผูกพันของทีมกับเครื่องมือเดิมก่อนตัดสินใจเปลี่ยน dependency', dimension: 'TF', pole: 'F' },
  { id: 103, text: 'ฉันสนับสนุนให้ทีมทำงาน overtime ถ้าข้อมูลชี้ว่าจำเป็นต่อการปิด sprint ให้ทัน', dimension: 'TF', pole: 'T' },
  { id: 104, text: 'ฉันไม่อยากให้ทีมทำงาน overtime แม้ deadline จะกระชั้นชิด เพราะห่วงสุขภาพใจของทุกคน', dimension: 'TF', pole: 'F' },
  { id: 105, text: 'ฉันให้เครดิตความสำเร็จของโปรเจกต์ตามสัดส่วนงานจริงที่แต่ละคนทำมากกว่าความรู้สึกเกรงใจ', dimension: 'TF', pole: 'T' },

  // JP — 106-120
  { id: 106, text: 'ฉันจัดทำ definition of done เป็น checklist ชัดเจนก่อนเริ่มงานทุกฟีเจอร์', dimension: 'JP', pole: 'J' },
  { id: 107, text: 'ฉันตัดสินใจว่างานเสร็จ "พอดี" จากความรู้สึกหน้างานมากกว่ายึด checklist ตายตัว', dimension: 'JP', pole: 'P' },
  { id: 108, text: 'ฉันชอบกำหนดวันที่ release ไว้ล่วงหน้าแน่นอนแล้วบริหารฟีเจอร์ให้ทันตามนั้น', dimension: 'JP', pole: 'J' },
  { id: 109, text: 'ฉันชอบปล่อย release เมื่อฟีเจอร์พร้อมจริงๆ มากกว่ายึดติดกับวันที่กำหนดไว้ล่วงหน้า', dimension: 'JP', pole: 'P' },
  { id: 110, text: 'ฉันจัดตารางประชุมและนัดหมายงานกับทีมล่วงหน้าอย่างเป็นระบบ', dimension: 'JP', pole: 'J' },
  { id: 111, text: 'ฉันสะดวกกับการนัดคุยงานแบบกะทันหันมากกว่าต้องจองตารางล่วงหน้า', dimension: 'JP', pole: 'P' },
  { id: 112, text: 'ฉันเขียนแผนทดสอบ test scenario ไว้ล่วงหน้าอย่างละเอียดก่อนเริ่ม QA จริง', dimension: 'JP', pole: 'J' },
  { id: 113, text: 'ฉันชอบทดสอบระบบแบบ exploratory คือลองสุ่มกดไปเรื่อยๆ ตามที่คิดขึ้นมาสด', dimension: 'JP', pole: 'P' },
  { id: 114, text: 'ฉันจัดระเบียบ backlog และ note งานของตัวเองอย่างเป็นหมวดหมู่ชัดเจนเสมอ', dimension: 'JP', pole: 'J' },
  { id: 115, text: 'บันทึกงานของฉันมักกระจัดกระจายเป็นโน้ตสั้นๆ ตามที่นึกขึ้นได้ในแต่ละตอน', dimension: 'JP', pole: 'P' },
  { id: 116, text: 'ฉันชอบล็อก architecture decision ให้แน่นอนตั้งแต่ต้นโปรเจกต์เพื่อไม่ให้แผนเปลี่ยนภายหลัง', dimension: 'JP', pole: 'J' },
  { id: 117, text: 'ฉันเปิดใจปรับ architecture decision ใหม่ได้เรื่อยๆ ตามที่โปรเจกต์พัฒนาไป', dimension: 'JP', pole: 'P' },
  { id: 118, text: 'ฉันทำตาม code review checklist ที่ทีมกำหนดไว้อย่างครบถ้วนทุกข้อก่อน approve', dimension: 'JP', pole: 'J' },
  { id: 119, text: 'ฉันรีวิวโค้ดตามความรู้สึกว่าจุดไหนน่าสนใจในตอนนั้นมากกว่าไล่ตาม checklist ตายตัว', dimension: 'JP', pole: 'P' },
  { id: 120, text: 'ฉันรู้สึกไม่สบายใจถ้าแผนงานที่วางไว้ล่วงหน้าถูกเปลี่ยนกะทันหันโดยไม่มีเหตุผลชัดเจน', dimension: 'JP', pole: 'J' },
];

export const programmingTypeTable: Record<string, MbtiTypeInfo> = {
  ISTJ: { title: 'ผู้ควบคุมคุณภาพโค้ด', description: 'คุณตรวจสอบรายละเอียดของโค้ดอย่างพิถีพิถันและทำงานตามมาตรฐานที่ทีมวางไว้อย่างเคร่งครัด เป็นคนที่ทีมไว้ใจให้ดูแลความถูกต้องของระบบก่อน deploy จริง', jobs: ['QA Engineer', 'Backend Developer', 'Database Administrator', 'Release Engineer'] },
  ISFJ: { title: 'ผู้ดูแลระบบอย่างใกล้ชิด', description: 'คุณใส่ใจทั้งความถูกต้องของระบบและความรู้สึกของเพื่อนร่วมทีม ทำงานเงียบๆ แต่สม่ำเสมอจนระบบมีเสถียรภาพในระยะยาว', jobs: ['Support Engineer', 'Maintenance Developer', 'System Administrator', 'Technical Support Lead'] },
  INFJ: { title: 'นักออกแบบระบบเชิงคุณค่า', description: 'คุณมองเห็นผลกระทบของระบบที่มีต่อผู้ใช้ในระยะยาวและอยากให้งานที่ทำสร้างความหมายจริง มีวิสัยทัศน์ชัดเจนแต่ยังคำนึงถึงความรู้สึกของทีม', jobs: ['Product Engineer', 'UX Engineer', 'Developer Advocate', 'Accessibility Engineer'] },
  INTJ: { title: 'นักวางสถาปัตยกรรมระยะยาว', description: 'คุณมองภาพรวมของระบบได้ทะลุปรุโปร่งและวางกลยุทธ์ทาง technical ระยะยาวอย่างเป็นระบบ ทำงานคนเดียวได้อย่างมีประสิทธิภาพสูง', jobs: ['Software Architect', 'Principal Engineer', 'System Designer', 'Technical Strategist'] },
  ISTP: { title: 'นักแก้ปัญหาเชิงเทคนิค', description: 'คุณถนัดลงมือแก้ปัญหาทางเทคนิคได้อย่างคล่องแคล่วและปรับวิธีทำงานตามสถานการณ์โดยไม่ยึดติดกับขั้นตอนเดิม เก่งเรื่อง debug และ troubleshoot', jobs: ['DevOps Engineer', 'Site Reliability Engineer', 'Embedded Developer', 'Infrastructure Engineer'] },
  ISFP: { title: 'นักพัฒนาสายละเอียด', description: 'คุณมีสายตาที่ละเอียดอ่อนต่อ user experience และสร้างงานที่ใช้งานได้ลื่นไหลอย่างเป็นธรรมชาติ ทำงานอย่างสงบและปล่อยให้ผลงานค่อยๆ ก่อตัวขึ้นเอง', jobs: ['Frontend Developer', 'UI Developer', 'Mobile App Developer', 'Game Developer'] },
  INFP: { title: 'นักพัฒนาเชิงอุดมคติ', description: 'คุณใส่คุณค่าและความหมายลงไปในผลิตภัณฑ์ที่สร้างทุกครั้ง อยากให้สิ่งที่เขียนช่วยเหลือผู้คนได้จริง สื่อสารแนวคิดผ่านโค้ดได้อย่างจริงใจ', jobs: ['Product Engineer', 'Open Source Contributor', 'EdTech Developer', 'Accessibility Developer'] },
  INTP: { title: 'นักทดลองแนวคิดเชิงระบบ', description: 'คุณชอบขบคิดหลักการเชิงลึกของ algorithm และทดลองแนวคิดใหม่ๆ อย่างเป็นเหตุเป็นผล มองหาคำตอบที่แตกต่างจากวิธีคิดทั่วไป', jobs: ['Research Engineer', 'Algorithm Engineer', 'AI/ML Engineer', 'Compiler Developer'] },
  ESTP: { title: 'นักลงมือแก้ปัญหาเฉพาะหน้า', description: 'คุณเรียนรู้และแก้ปัญหาได้รวดเร็วในสถานการณ์กดดัน เช่นตอน incident เกิดขึ้นจริง ชอบลงมือทำจริงมากกว่าวางแผนนานๆ', jobs: ['Incident Responder', 'On-call Engineer', 'Rapid Prototyper', 'Hackathon Developer'] },
  ESFP: { title: 'นักสร้างบรรยากาศทีมพัฒนา', description: 'คุณมีพลังบวกและทำให้บรรยากาศการทำงานในทีม dev สนุกสนาน ถนัดสื่อสารเรื่องเทคนิคให้คนอื่นเข้าใจง่ายและอินไปกับงานได้', jobs: ['Developer Relations', 'Demo Engineer', 'Community Manager', 'Junior Team Lead'] },
  ENFP: { title: 'นักจุดประกายไอเดียเทคโนโลยี', description: 'คุณเต็มไปด้วยพลังและไอเดียใหม่ๆ ไม่หยุดหย่อน ชอบชวนทีมระดมสมองหา solution ใหม่และสร้างแรงบันดาลใจให้กล้าคิดต่าง', jobs: ['Innovation Engineer', 'Startup Developer', 'Product Engineer', 'Hackathon Lead'] },
  ENTP: { title: 'นักท้าทายแนวทางเดิม', description: 'คุณชอบตั้งคำถามกับวิธีแก้ปัญหาแบบเดิมๆ และเสนอทางเลือกทาง technical ที่แปลกใหม่อยู่เสมอ ถกเถียงไอเดียได้อย่างคล่องแคล่วและสนุกกับการทดลอง', jobs: ['Full-stack Developer', 'Tech Evangelist', 'R&D Engineer', 'Platform Engineer'] },
  ESTJ: { title: 'ผู้จัดการสายการพัฒนา', description: 'คุณบริหารจัดการขั้นตอนการพัฒนาให้เดินหน้าตามแผนได้อย่างเด็ดขาดและมีระบบ เป็นคนที่ทีมพึ่งพาได้เมื่อต้อง ship งานให้ตรงเวลา', jobs: ['Engineering Manager', 'Project Lead', 'Release Manager', 'Scrum Master'] },
  ESFJ: { title: 'ผู้ประสานทีมพัฒนา', description: 'คุณดูแลให้ทุกคนในทีมพัฒนาทำงานร่วมกันได้อย่างราบรื่นและรู้สึกได้รับการสนับสนุน ใส่ใจทั้งคุณภาพงานและความสัมพันธ์ในทีม', jobs: ['Team Lead', 'Agile Coach', 'Technical Project Coordinator', 'QA Lead'] },
  ENFJ: { title: 'ผู้นำทีมพัฒนาที่สร้างแรงบันดาลใจ', description: 'คุณสร้างแรงบันดาลใจให้ทีมพัฒนาทำงานร่วมกันไปในทิศทางเดียวกัน เข้าใจความต้องการของทั้งทีมและผู้ใช้ได้อย่างลึกซึ้ง', jobs: ['Engineering Manager', 'Tech Lead', 'Developer Experience Lead', 'Mentor Engineer'] },
  ENTJ: { title: 'ผู้กำหนดทิศทางเทคโนโลยี', description: 'คุณมองเห็นภาพรวมของกลยุทธ์ทาง technical และตัดสินใจได้อย่างเด็ดขาดเพื่อผลักดันงานให้ไปถึงเป้าหมาย เป็นผู้นำที่กล้าวางวิสัยทัศน์ใหม่ให้ทีม', jobs: ['CTO', 'VP of Engineering', 'Software Architect', 'Technical Director'] },
};
